# Generated by Django 5.1.3 on 2024-11-24 13:51

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project'),
        ),
    ]
