# Generated by Django 5.1.3 on 2024-12-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_commentary_image_alter_image_image_and_more'),
        ('users', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorate', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorate', to='users.userprofile')),
            ],
        ),
    ]
